jobs:
  - script: >
      pipelineJob('backstage-lab-basic') {
        definition {
          cps {
            script("""pipeline {
              agent any
              stages {
                stage('get-rhtap-logs') {
                  steps {
                    sh 'curl -sSfL https://raw.githubusercontent.com/CryptoRodeo/backstage-lab/main/sbom-logs'
                  }
                }
              }
            }""")
            sandbox(true)
          }
        }
      }

  - script: >
      multibranchPipelineJob('backstage-lab') {
        branchSources {
          git {
            id('backstage-lab')
            remote('https://github.com/cryptorodeo/backstage-lab.git')
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath('manifests/jenkins/Jenkinsfile')
          }
        }
      }
