apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: backstage-rollouts-token
  namespace: backstage-argocd
  annotations:
    kubernetes.io/service-account.name: backstage-rollouts
  labels:
    backstage.io/token: "rollouts-testing"


