apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-rollouts
  namespace: backstage-argocd
  labels:
    backstage.io/service-account: "rollouts-testing"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-rollouts-testing-binding
  labels:
    backstage.io/rbac: "rollouts-testing"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-rollouts-testing
subjects:
- kind: ServiceAccount
  name: backstage-rollouts
  namespace: backstage-argocd


