apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: backstage-llms
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 80Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data
  namespace: backstage-llms
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
