apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: backstage-llms
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: backstage-test-llms
  ports:
    - name: http
      port: 11434
      targetPort: ollama-host

