apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: backstage-tekton-token
  namespace: backstage-tekton-pipelines
  annotations:
    kubernetes.io/service-account.name: backstage-tekton
