pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                script  {
                     sh  '''
                          curl https://raw.githubusercontent.com/cryptorodeo/backstage-lab/refs/heads/main/sbom-logs
                        '''
                    }
                }
            }
        }
    }
