apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/CryptoRodeo/backstage-lab.git
        revision: main
        directories:
          - path: manifests/*/overlays/*
  template:
    metadata:
      name: '{{path[1]}}-{{path.basename}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: 'backstage-{{path[1]}}' # e.g. tekton from manifests/tekton/overlays/default
      source:
        repoURL: https://github.com/CryptoRodeo/backstage-lab.git
        targetRevision: main
        path: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
